# Set base URL for site - should end with a trailing slash
baseUrl = "https://example.org/"

theme = "slick"

# Site title (not shown if commented out or set to false)
# (If you disable this, add some link on the index page inside menu.main,
#  otherwise your visitors will get confused and lost...)
title = "Blackhoodie"

languageCode = "en"
defaultContentLanguage = "en-us"

# Will appear below the footer links with a © sign and the current year
copyright = "Blackhoodie — Women who RE."

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true               # Allow html (needed for some shortcodes)
    [markup.highlight]
        codeFences = true               # Enable highlighting inside codefences
        guessSyntax = true              # Highlight code without language tag
        noClasses = false               # Use the theme's style sheet

canonifyURLs = true
preserveTaxonomyNames = true

# Configure pagination
paginate = 10
paginatePath = "page"

[params]
    # Site subtitle (not shown if commented out or set to false)
    # subtitle = "Just another site"

    # Site description
    # description = "Example site for Slick Hugo theme"

    # Favicon file (relative to baseURL - place below static or assets folder)
    favicon = "favicon.png"
    # Custom css file (relative to baseURL - place below static or assets folder)
    css = "custom.css"

    # Define formatting of dates
    # (optional, falls back to RFC822 format if not set)
    # For reference to date and time formatting, see:
    # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
    # Make sure to set showMetaDates to true to see any dates
    # dateFmt = "Mon, 02 Jan 2006 15:04:05 MST"
    dateFmt = "Mon, 02 Jan 2006"

    # Customize the text of the 404 page here
    errorPageText = "There's nothing to see here, please move along!"

    # Header with title/subtitle can be disabled here.
    # (If you disable this, add some link on the index page inside menu.main,
    #  otherwise your visitors will get confused and lost...)
    showNavHeader = true

    # Decide if only summaries are shown on the main page or the full content
    showFullContent = true

    # If false no pagination is shown when there is nothing to paginate
    showEmptyPagination = true

    # If false the dates for the posts are not shown
    showMetaDates = true

    # If false the taxonomy links for the posts are not shown
    showMetaLinks = true

    # Uses Hugo internal templates if set
    opengraph = false
    schema = false
    twitter_cards = false


# Define all supported taxonomies
[taxonomies]
    tags = "tags"
    categories = "categories"


[author]
    name = "Some Author"
    email = "mail@example.org"


[services.rss]
    # limit the length of the rss feed (default: unlimited)
    limit = 0


[menu]

    # Configure main menu entries (header)
    # Currently set to list all taxonomies and posts
    [[menu.main]]
        identifier = "post"
        name = "Posts"
        title = "All posts"
        url = "/posts/"
        weight = 1



    # Add some footer links to your likings
    [[menu.footer]]
        name = "GitHub"
        title = "Theme repository"
        url = "https://github.com/spookey/slick"
        weight = 1

    [[menu.footer]]
        name = "Slick"
        title = "Theme page on gohugo.io"
        url = "https://themes.gohugo.io/slick"
        weight = 2

